### ISSUE TITLE
`save_ELAN()` should have optional `newpath` arg

### ISSUE THREAD

**Issue by djvill** [AlejandroCiuba/elan_data#1]
Users will likely want the option of saving eaf at a different path:
https://github.com/AlejandroCiuba/elan_data/blob/9012a9ce34810f2080431ebd585e82fa06e016a8/src/elan_data/__init__.py#L1115

**Comment by AlejandroCiuba** [comment]
I like the idea, but overall the programmer should create the filepath to the `ELAN_Data` instance upon creation via one of the constructor methods. Or, if they want, they can access the `file` attribute directly after creation to change the path directory.

**Comment by AlejandroCiuba** [comment]
A rename argument has been added to allow the user to change the name of the saved file. However, this also changes the name of the instance.
