### ISSUE TITLE
`overlaps()`: Identify problematic seg_id

### ISSUE THREAD

**Issue by djvill** [AlejandroCiuba/elan_data#2]
The error message here should ID the problematic seg_id (e.g., rather than `No segment matches the given seg_id value`, `No segment matches seg_id value a381`). If a user is looping over a bunch of rows (e.g., `[eaf.overlaps(x, tiers=tiers) for x in eaf.tier_data.SEGMENT_ID]]`), it'd be good to know which one triggered the error.

https://github.com/AlejandroCiuba/elan_data/blob/9012a9ce34810f2080431ebd585e82fa06e016a8/src/elan_data/__init__.py#L500-L501

**Comment by AlejandroCiuba** [comment]
Resolved with additional information in the error.
