### ISSUE TITLE
`add_audio()` ValueError: relative path can't be expressed as a file URI

### ISSUE THREAD

**Issue by djvill** [AlejandroCiuba/elan_data#3]
This line yields an error on Windows:

https://github.com/AlejandroCiuba/elan_data/blob/9012a9ce34810f2080431ebd585e82fa06e016a8/src/elan_data/__init__.py#L774

I think `Path.as_uri()` doesn't like `file:/` in its input:

```python
file = 'final/LV10interview3.eaf'
audio = Path('input/LV10interview3.wav')
ed_obj = ELAN_Data(file)
Path(audio.absolute().as_uri())
# WindowsPath('file:/C:/Users/DAV49/batchalign-workspace/beam100/input/LV10interview3.wav')
ed_obj.audio = Path(audio.absolute().as_uri())
ed_obj.audio.as_uri()
# Traceback (most recent call last):
#  File "<pyshell#81>", line 1, in <module>
#    ed_obj.audio.as_uri()
#  File "C:\Users\DAV49\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 649, in as_uri
#    raise ValueError("relative path can't be expressed as a file URI")
# ValueError: relative path can't be expressed as a file URI
```

Since `self.audio` is already guaranteed to be a URI path [above](https://github.com/AlejandroCiuba/elan_data/blob/main/src/elan_data/__init__.py#L765-L770), it should suffice to just use `self.audio` here.

**Comment by AlejandroCiuba** [comment]
Your pull request has been merged

**Comment by AlejandroCiuba** [comment]
I fixed additional bugs with the URI formatting and the `add_audio` function and everything seems to be working as of now.
